version: '3.8'

services:
  db:
    container_name: HRS-DB
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}
      POSTGRES_DB: ${DB_PASSWORD}
    volumes:
      - hrs_data:/var/lib/postgresql/data
    networks:
      - "hrs.network"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080"
    depends_on:
      - db
    restart: on-failure
    networks:
      - "hrs.network"
    deploy:
      replicas: 3

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - app
#    ports:
#      - "80:80"
#    networks:
#      - "hrs.network"

volumes:
  hrs_data:
networks:
  hrs.network: