version: '3.8'

services:
  db:
    container_name: HRS-DB
    image: postgres:latest
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - hrs_data:/var/lib/postgresql/data
    networks:
      - "hrs.network"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

    restart: on-failure
    networks:
      - "hrs.network"
    deploy:
      replicas: 3

  # reverse proxy
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - "hrs.network"

volumes:
  hrs_data:
networks:
  hrs.network: